@include('layouts.header')
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  @include('layouts.navbar')
  @include('layouts.menubar')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>Payroll</h1>
      <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="/employee"> Employees</a></li>
        <li class="active">Payroll</li>
      </ol>
    </section>
    <!-- Main content -->
    <section class="content">
      
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header with-border">
              
              <button data-id="" data-target="#generate" data-toggle="modal" class="btn btn-primary" style="float: right;"><i class="fa fa-plus"></i> Generate Payroll</button>
            </div>
            <div class="box-body">
              
              <table id="example2" class="table table-bordered">
                <thead>
                  <th class="hidden"></th>
                  
                  <th>No.</th>
                  <th>Month</th>
                  <th>Year</th>
                  <th>Generated By</th>
                  <th>Date</th>
                  <th>Tools</th>
                </thead>
                <tbody>
                  @foreach($payrolls as $payroll)
                    <tr>
                      <td>{{ $payroll->id }}</td>
                      <td>{{ $payroll->month }}</td>
                      <td>{{ $payroll->year }}</td>
                      <td>{{ $payroll->generated_by }}</td>
                      <td>{{ $payroll->date }}</td>
                      <td>
                        <a href="/payroll_detail/{{ $payroll->id }}" class="btn btn-success btn-sm" ><i class="fa fa-eye"></i> View</a>
                        <a href="/payroll_delete/{{ $payroll->id }}" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i> Delete</a>

                      </td>
                    </tr>
                    @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </section>   
  </div>
    
  @include('layouts.footer')
  @include('layouts.payroll_modal')
</div>
@include('layouts.scripts')
<script>
$(function(){
 
  $('#generate').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) 
  var id = button.data('id');
  // alert(id)
    $('#edit_sal_action').attr('action', '/edit_sal/'+id)
  var modal = $(this)
  modal.find('.modal-body #add_employee_id').val(id)
  });
  $('#edit').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) 
  var salary = button.data('mysalary')
  var effective_date = button.data('myeffectivedate') 
  var end_date = button.data('myenddate')
  var employee_id = button.data('myemployeeid')
  var id = button.data('id');
    $('#edit_sal_action').attr('action', '/edit_sal/'+id)
  var modal = $(this)
  modal.find('.modal-body #edit_employee_id').val(employee_id)
  modal.find('.modal-body #edit_salary').val(salary)
  modal.find('.modal-body #edit_effective_date').val(effective_date)
  modal.find('.modal-body #edit_end_date').val(end_date)
})

  $('#delete').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget) 
    var salary = button.data('mysalary')
    var effective_date = button.data('myeffectivedate') 
    var end_date = button.data('myenddate')
    var employee_id = button.data('myemployeeid')
    var id = button.data('id');
    $('#del_sal_action').attr('action', '/del_sal/'+id)
    var modal = $(this)
    modal.find('.modal-body #del_employee_id').val(employee_id)
    modal.find('.modal-body #del_salary').text(salary + ' ' + effective_date + ' - ' + end_date)
  })
});
</script>
</body>
</html>
